; rm2mmc3.inc
; Copyright 2022 Justin Olbrantz (Quantam)
; API include for Rockman 2. See readme for usage instructions.

; This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.

.include "mm2mmc3regs.inc"

Switch16kBank := $c000
SwitchBank8 := $d0a2
SwitchBankA := $d0aa
Switch16kBankUnsafe := $c05e
SwitchBank8Unsafe := $c01f
SwitchBankAUnsafe := $c024
